<?php


namespace App\Promo;


use App\Cart;

class BuyTwoGetOne extends Promo
{
    const DIVISOR = 2;
    const GIVE = 1;

    /**
     * @param Cart $cart
     */
    public function apply(Cart $cart)
    {
        parent::apply($cart); // TODO: Change the autogenerated stub

        $discount = 0;
        $items = $this->getCart()->getItems();
        foreach ($items as $item) {
            $mod = floor($item->getQuantity() / self::DIVISOR);
            if ($mod > 0) {
                $addQuantity = $mod * self::GIVE;
                $updateQuantity = $item->getQuantity() + $addQuantity;
                $item->setQuantity($updateQuantity);
                $discount += $mod * $item->getPrice();
            }
        }
        $this->updateItems($items);
        $this->setDiscount($discount);
    }
}